#include "global.h"
#include "hardware.h"
#include "timer.h"
#include "init.h"
#include "callback.h"
#include "pwm.h"
#include "adc.h"
#include "interrupt.h"
#include "delay.h"
#include "state.h"

// Event functions (functions that generate events)
void QueueButton(void);
void TimerTick(void);

// Event definitions (events generated by the Event Functions)
enum EVENT {IDLE = 0, BUTTON_DOWN, TIMER_TICK};

// State functions (functions that consume events)
void state_idle(uint8_t event);
void state_blink_red(uint8_t event);
void state_blink_green(uint8_t event);

// Transition rules
transition state_transitions[] =
{
    {state_idle,        IDLE,        state_idle       },
    {state_idle,        BUTTON_DOWN, state_blink_red  },
    {state_blink_red,   IDLE,        state_blink_red  },
    {state_blink_red,   BUTTON_DOWN, state_blink_green},
    {state_blink_green, IDLE,        state_blink_green},
    {state_blink_green, BUTTON_DOWN, state_idle       }
};

State state;

void main(void)
{
    WD_STOP();
    SET_CLOCK(16);
    CallbackTimerInit();
    HardwareInit();

	AttachInterrupt(1,3,QueueButton,FALLING_EDGE);
    CallbackRegister(TimerTick, 100ul * _millisecond);
    StateMachineInit(state_transitions, sizeof(state_transitions));
    _EINT();

    // initial state
    state = state_idle;

    while (1)
    {
        state(CheckEventQueue());
    }
}

void state_idle(uint8_t event)
{
    switch(event)
    {
        case BUTTON_DOWN:
            CallbackMode(TimerTick, ENABLED);
            break;
        default:
            break;
    }
    state = LookupTransition(state, event);
}

void state_blink_red(uint8_t event)
{
    switch(event)
    {
        case TIMER_TICK:
            RED_LED_TOGGLE();
            break;
        case BUTTON_DOWN:
            RED_LED_OFF();
            GREEN_LED_OFF();
            break;
        default:
            break;
    }
    state = LookupTransition(state, event);
}

void state_blink_green(uint8_t event)
{
    switch(event)
    {
        case TIMER_TICK:
            GREEN_LED_TOGGLE();
            break;
        case BUTTON_DOWN:
            RED_LED_OFF();
            GREEN_LED_OFF();
            CallbackMode(TimerTick, DISABLED);
            break;
        default:
            break;
    }
    state = LookupTransition(state, event);
}

void QueueButton(void)
{
    EnqueueEvent(BUTTON_DOWN);
}
void TimerTick(void)
{
    EnqueueEvent(TIMER_TICK);
}
